# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddaaa820ebf5c7a3f8fc08a010feaa1716a755c640b0215b1f9ab3863353d553968fab17053004f6b9fc6a1c67ebeca32010efc70ed2aa62151f15438d7353a0

test:
  secret_key_base: 28d435213ae69205b322259c7874be877a80dfe11e29be0149a699bee3c5d0a2cb7cab7c34896a8058654e63ff611828b766b8bd416200e859588bf2e3851c3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
